name: event_logger
description: A new Flutter package for logging events.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^6.1.1
  sqflite: ^2.4.2
  flutter_local_notifications: ^19.5.0
  permission_handler: ^12.0.1
  path_provider: ^2.1.5
  path: ^1.9.1
  firebase_messaging: 16.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
